version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
      - ./.env.dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
      - ./.env.dev
    ports:
      - "${HTTPSERVER_PORT}:3031"
    depends_on:
      - db

volumes:
  db-data: