version: '3.8'

services:
  db:
    container_name: microservice-db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
      - .env.production
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"

  app:
    container_name: microservice-app
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    env_file:
      - ./.env
      - .env.production
    ports:
      - "${HTTPSERVER_PORT}:3031"
    depends_on:
      - db

volumes:
  db-data: